version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
