version: '3.8'

services:
  app:
    image: 515966527734.dkr.ecr.ap-northeast-2.amazonaws.com/tourgether-server:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - postgres-db
      - redis
    restart: always
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

