spring:
  application:
    name: tourgether

  jwt:
    access:
      secret-key: ${JWT_ACCESS_SECRET_KEY}
    refresh:
      secret-key: ${JWT_REFRESH_SECRET_KEY}

  oauth2:
    client:
      provider:
        kakao:
          url: "https://kapi.kakao.com/v2/user/me"
        naver:
          url: "https://openapi.naver.com/v1/nid/me"
        google:
          url: "https://oauth2.googleapis.com/tokeninfo?id_token="

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass123

  data:
    redis:
      host: localhost
      port: 6379
  #      password:
  #      database:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

odsay:
  api:
    key: ${ODSAY_API_KEY}
