spring:
  application:
    name: tourgether

  jwt:
    access:
      secret-key: ${JWT_ACCESS_SECRET_KEY}
    refresh:
      secret-key: ${JWT_REFRESH_SECRET_KEY}

  oauth2:
    client:
      provider:
        kakao:
          userinfo-uri: "https://kapi.kakao.com/v2/user/me"
          unlink-uri: "https://kapi.kakao.com/v1/user/unlink"
        naver:
          userinfo-uri: "https://openapi.naver.com/v1/nid/me"
          unlink-uri: "https://nid.naver.com/oauth2.0/token	"
          client-id: ${NAVER_CLIENT_ID}
          client_secret: ${NAVER_CLIENT_SECRET}
        google:
          userinfo-uri: "https://oauth2.googleapis.com/tokeninfo?id_token="
          unlink-uri:

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass123

  data:
    redis:
      host: redis-db
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

odsay:
  api:
    key: ${ODSAY_API_KEY}
